name: Analyze
on:
  push:
permissions: read-all
jobs:
  Scorecard:
    if: github.ref_name == github.event.repository.default_branch
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      security-events: write # to upload the results to code-scanning dashboard
      id-token: write        # to publish_results and get a badge
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish_results: true
        results_file: results.sarif
        results_format: sarif
    - uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9
      with:
        sarif_file: results.sarif
