name: Test
on:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: [3.3, 3.4, 4.0]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - run: bundle exec rake
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637
      with:
        oidc: true
        files: coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: bundle exec rubocop
    - run: bundle exec inch --pedantic
